# Generated by Django 4.2.7 on 2023-11-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('rating', models.FloatField()),
                ('author_name', models.CharField(max_length=255)),
            ],
        ),
    ]
