# Generated by Django 4.2.7 on 2023-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='place_id',
        ),
        migrations.AddField(
            model_name='review',
            name='profile_photo_url',
            field=models.URLField(default='default_photo_url_here'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
